### creates  a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "tharaniGodMode",
  "email" : "godmode@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "2006-12-12",
  "registeredDate": "2026-06-17"
}

###0
