### PUT for update the patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name" : "tharani123  ",
  "email" : "mano  @gmail.com",
  "address": "123 main street",
  "dateOfBirth": "2006-05-12"
}

###